
export const columns = [
    {title: 'avatar', dataIndex: 'avatar', fixed: 'left' },
    {title: 'name',dataIndex: 'name', fixed: 'left' },
    {title: 'age', dataIndex: 'age'},
    {title: 'address', dataIndex: 'address' },
    {title: 'avatar', dataIndex: 'avatar' },
    {title: 'name',dataIndex: 'name' },
    {title: 'age', dataIndex: 'age'},
    {title: 'address', dataIndex: 'address' },
    {title: 'avatar', dataIndex: 'avatar' },
    {title: 'name',dataIndex: 'name' },
    {title: 'age', dataIndex: 'age'},
    {title: 'address', dataIndex: 'address' },
    {title: 'avatar', dataIndex: 'avatar' },
    {title: 'name',dataIndex: 'name' },
    {title: 'age', dataIndex: 'age', fixed: 'right' },
    {title: 'address', dataIndex: 'address', fixed: 'right' }
];

export const dataSource = [
    {avatar: '🎅🏻',name: 'chuanJianGuo', age: 74, address: 'America'},
    {avatar: '👵🏻', name: 'caiEnglish', age: 63, address: 'China Taiwan'},
    {avatar: '-',name: 'trump', age: 74, address: 'America'},
    {avatar: '-',name: 'johnson', age: 70, address: 'England'},
    {avatar: '🎅🏻',name: 'chuanJianGuo', age: 74, address: 'America'},
    {avatar: '👵🏻', name: 'caiEnglish', age: 63, address: 'China Taiwan'},
    {avatar: '-',name: 'trump', age: 74, address: 'America'},
    {avatar: '-',name: 'johnson', age: 70, address: 'England'},
    {avatar: '🎅🏻',name: 'chuanJianGuo', age: 74, address: 'America'},
    {avatar: '👵🏻', name: 'caiEnglish', age: 63, address: 'China Taiwan'},
    {avatar: '-',name: 'trump', age: 74, address: 'America'},
    {avatar: '-',name: 'johnson', age: 70, address: 'England'},
    {avatar: '🎅🏻',name: 'chuanJianGuo', age: 74, address: 'America'},
    {avatar: '👵🏻', name: 'caiEnglish', age: 63, address: 'China Taiwan'},
    {avatar: '-',name: 'trump', age: 74, address: 'America'},
    {avatar: '-',name: 'johnson', age: 70, address: 'England'},
    {avatar: '🎅🏻',name: 'chuanJianGuo', age: 74, address: 'America'},
    {avatar: '👵🏻', name: 'caiEnglish', age: 63, address: 'China Taiwan'},
    {avatar: '-',name: 'trump', age: 74, address: 'America'},
    {avatar: '-',name: 'johnson', age: 70, address: 'England'},
    {avatar: '🎅🏻',name: 'chuanJianGuo', age: 74, address: 'America'},
    {avatar: '👵🏻', name: 'caiEnglish', age: 63, address: 'China Taiwan'},
    {avatar: '-',name: 'trump', age: 74, address: 'America'},
    {avatar: '-',name: 'johnson', age: 70, address: 'England'},
    {avatar: '🎅🏻',name: 'chuanJianGuo', age: 74, address: 'America'},
    {avatar: '👵🏻', name: 'caiEnglish', age: 63, address: 'China Taiwan'},
    {avatar: '-',name: 'trump', age: 74, address: 'America'},
    {avatar: '-',name: 'johnson', age: 70, address: 'England'},
    {avatar: '🎅🏻',name: 'chuanJianGuo', age: 74, address: 'America'},
    {avatar: '👵🏻', name: 'caiEnglish', age: 63, address: 'China Taiwan'},
    {avatar: '-',name: 'trump', age: 74, address: 'America'},
    {avatar: '-',name: 'johnson', age: 70, address: 'England'},
    {avatar: '🎅🏻',name: 'chuanJianGuo', age: 74, address: 'America'},
    {avatar: '👵🏻', name: 'caiEnglish', age: 63, address: 'China Taiwan'},
    {avatar: '-',name: 'trump', age: 74, address: 'America'},
    {avatar: '-',name: 'johnson', age: 70, address: 'England'},
];
