import Head from 'next/head'
import styles from '../styles/Home.module.css'

import ZIndex1 from "../test/zIndex-1";
import Absolute1 from "../test/absolute1";
import Scrollable1 from "../test/scrollable";
import Animation from "../test/animation";


export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>ZIndex</h1>
                <ZIndex1 />

                <h1 className={styles.title}>Absolute</h1>
                <Absolute1 />

                <h1 className={styles.title}>Scrollable</h1>
                <Scrollable1></Scrollable1>

                <h1 className={styles.title}>Animation</h1>
                <Animation />
            </main>
        </div>
    )
}
